### ISSUE TITLE
losses become nan after epoch 1 

### ISSUE THREAD

**Issue by zwbx** [rickgroen/cov-weighting#3]
I just use the cov-weighting in my training code
it turns out that losses become nan after epoch 1 
Would I ask have you ever encountered this condition before?

**Comment by rickgroen** [comment]
Hi,

No, I haven't seen that before. 
Could it be one of your losses approaches zero in the first epoch? I think that if it does, maybe you could get unstable behaviour at [line 56](https://github.com/rickgroen/cov-weighting/blob/64c296679cd37e724a03c6dc107606f7048aec96/losses/covweighting_loss.py#L56). Potentially, adding a small constant value (1e-8 for example) to the denominator could alleviate those problems.
However, if you do have a loss that approaches zero that quickly, it may not be a very informative loss to begin with?

Regards,
Rick

**Comment by zwbx** [comment]
This is exactly the problem. Thank you.
