### ISSUE TITLE
Your method of using GradNorm(2018)?

### ISSUE THREAD

**Issue by daeunni** [rickgroen/cov-weighting#6]
Hi, 
Thank you for your nice work. :) 

btw, I wonder your method of using the GradNorm(2018) in Kitti dataset. 
(Because GN doesn't have an official code) 

did you modified this reporisitory codes for applying gradnorm? 

Best, 
Daeun Lee

**Comment by rickgroen** [comment]
Hi Daeun Lee,

Thank you very much!
Yes, you are right. This repository of code is a cleaned version of the code I used to write the paper. I tried to give a basic working example of the method, such that people could replicate it. I think there are a few implementations of Gradnorm on github, but unfortunately not the official author's implementation.
If you like I can see about adding Gradnorm as one of the methods, but just a heads-up, it will probably be after the ECCV deadline in March.

Best,
Rick

**Comment by daeunni** [comment]
thanks :)
